# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 20:23
from __future__ import unicode_literals

import apps.events.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('artists', models.CharField(max_length=255, verbose_name='Артисты')),
                ('style', models.CharField(max_length=255, verbose_name='Стиль')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start', models.TimeField(verbose_name='Начало')),
                ('discounts', models.CharField(blank=True, max_length=255, null=True, verbose_name='Акции')),
                ('price', models.IntegerField(blank=True, default=0, verbose_name='Вход')),
                ('is_special', models.BooleanField(default=False, verbose_name='Особенное мероприятие')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активировано')),
                ('poster', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=apps.events.models.upload_location, verbose_name='Афиша')),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True, verbose_name='Дополнительно')),
            ],
        ),
    ]
