# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-18 18:59
from __future__ import unicode_literals

import apps.events.models
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20160607_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('style', models.CharField(max_length=255, verbose_name='Стиль')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Биография')),
                ('img', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=apps.events.models.artists_upload_location, verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Артист',
                'verbose_name_plural': 'Артисты',
            },
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='style',
        ),
        migrations.AlterField(
            model_name='event',
            name='artists',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artists', to='events.Artist', verbose_name='Артисты'),
        ),
    ]
