# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-18 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20160618_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='artists',
        ),
        migrations.AddField(
            model_name='event',
            name='artists',
            field=models.ManyToManyField(related_name='artists', to='events.Artist', verbose_name='Артисты'),
        ),
    ]
