# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 17:49
from __future__ import unicode_literals

import apps.menu.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('detail', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Детально')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Созданно')),
                ('photo', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=apps.menu.models.upload_location, verbose_name='Фото')),
                ('is_lunch', models.BooleanField(default=False, verbose_name='Бизнесс ланч')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активированно')),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True, verbose_name='Дополнительно')),
            ],
            options={
                'verbose_name_plural': 'Меню',
                'verbose_name': 'Меню',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(verbose_name='Количество')),
                ('measure', models.CharField(max_length=64, verbose_name='Ед. измерения')),
                ('value', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Значение')),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True, verbose_name='Дополнительно')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='menu.Menu', verbose_name='Меню')),
            ],
            options={
                'verbose_name_plural': 'Стоимость',
                'verbose_name': 'Стоимость',
            },
        ),
    ]
