# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-23 11:44
from __future__ import unicode_literals

import apps.menu.models
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True, verbose_name='Дополнительно')),
            ],
            options={
                'verbose_name_plural': 'Категории',
                'verbose_name': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('code', models.CharField(max_length=128, unique=True, verbose_name='Код')),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True, verbose_name='Дополнительно')),
            ],
            options={
                'verbose_name_plural': 'Группы',
                'verbose_name': 'Группа',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('detail', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Детально')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Созданно')),
                ('photo', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=apps.menu.models.menu_upload_location, verbose_name='Фото')),
                ('photo_base64', models.CharField(blank=True, default='base', max_length=255, verbose_name='Фото Base64')),
                ('is_lunch', models.BooleanField(default=False, verbose_name='Бизнесс ланч')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активированно')),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True, verbose_name='Дополнительно')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='menu.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name_plural': 'Меню',
                'verbose_name': 'Меню',
            },
        ),
        migrations.CreateModel(
            name='MenuSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_count', models.IntegerField(blank=True, default=1)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(verbose_name='Количество')),
                ('measure', models.CharField(max_length=64, verbose_name='Ед. измерения')),
                ('value', models.IntegerField(verbose_name='Значение')),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True, verbose_name='Дополнительно')),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='menu.Menu', verbose_name='Меню')),
            ],
            options={
                'verbose_name_plural': 'Стоимость',
                'verbose_name': 'Стоимость',
            },
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Созданно')),
                ('photo', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=apps.menu.models.set_upload_location, verbose_name='Фото')),
                ('photo_base64', models.CharField(blank=True, default='base', max_length=255, verbose_name='Фото Base64')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активированно')),
                ('additional', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, null=True, size=None, verbose_name='Дополнительные блюда')),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True, verbose_name='Дополнительно')),
                ('menu', models.ManyToManyField(related_name='menus', through='menu.MenuSet', to='menu.Menu', verbose_name='Позиции меню')),
            ],
            options={
                'verbose_name_plural': 'Наборы',
                'verbose_name': 'Набор',
            },
        ),
        migrations.AddField(
            model_name='price',
            name='set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='menu.Set', verbose_name='Набор'),
        ),
        migrations.AddField(
            model_name='menuset',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Set'),
        ),
        migrations.AddField(
            model_name='category',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='menu.Group', verbose_name='Группа'),
        ),
    ]
