# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.TextField(default='default description', verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
