# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-18 20:12
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20160618_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='detail',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Детально'),
        ),
    ]
