# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-27 10:36
from __future__ import unicode_literals

import apps.gallery.models
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20160618_1938'),
        ('gallery', '0002_auto_20160607_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='event',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='album', to='events.Event', verbose_name='Мероприятие'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='main_image',
            field=versatileimagefield.fields.VersatileImageField(default=1, upload_to=apps.gallery.models.album_upload_location, verbose_name='Фото'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='album',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gallery.Album', verbose_name='Альбом'),
            preserve_default=False,
        ),
    ]
