# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 21:26
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('is_vip', models.BooleanField(default=False, verbose_name='VIP')),
                ('phone_number', models.CharField(max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен иметь следующий фомат: '+999999999'. до 15 цифр.", regex='^\\+?1?\\d{4,17}$')], verbose_name='Телефон')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('deposite', models.PositiveIntegerField(blank=True, null=True, verbose_name='Депозит')),
                ('count_people', models.PositiveSmallIntegerField(verbose_name='Количество человек')),
                ('status', models.CharField(blank=True, default='Ожидает', max_length=128, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Коментарий')),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, verbose_name='Экстра')),
            ],
            options={
                'verbose_name': 'Резервация',
                'verbose_name_plural': 'Резервация',
            },
        ),
    ]
