# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(blank=True, choices=[('w', 'Ожидает'), ('c', 'Подтверждено'), ('d', 'Отменено')], default='w', max_length=2, verbose_name='Статус'),
        ),
    ]
